#!/usr/bin/env bash

set -eou pipefail

# switch branches based on index selection

readonly green="$(tput -T $TERM setaf 2)"
readonly reset="$(tput -T $TERM sgr0)"

branch_list=$(git branch)

i=0
declare -a branches
while IFS= read -r line; do
  printf "%s:\t%s\n" "$i" "$line"
  branches+=("$line")
  let i=i+1
done <<< "$branch_list"

len="${#branches[*]}"
index="$len"
while
  read -p "${green}Select branch #: ${reset}" index
  [[ ! $index -lt $len ]]
do echo "[ERROR] index out of bounds"; done

# use xargs to trim whitespace
selection=$(echo "${branches[index]}" | xargs)

# remove "* " if the current branch was selected
[[ "$selection" =~ ^"*" ]] && selection="${selection//* }"

git checkout "$selection"

# show last log
git log -n 1
