#!/usr/bin/env bash

# Show which files are getting changed most often in the repository.

set -eou pipefail

git log --all -M -C --name-only --format='format:' "$@" -- . ':(exclude)vendor' | \
  sort | \
  grep -v '^$' | \
  uniq -c | \
  sort -n | \
  awk 'BEGIN {print "count\tfile"} {print $1 "\t" $2}'
